# Generated by Django 3.2.3 on 2021-06-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
